[package]
name = "konstruo_ui"
version = { workspace = true }
edition = "2021"

[dependencies]
bevy = { workspace = true }
konstruo_core = { workspace = true }
konstruo_environment = { workspace = true }
konstruo_geometry = { workspace = true }

[lints]
workspace = true
