[package]
name = "konstruo_beziers"
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
kurbo = { workspace = true }
konstruo_core = { workspace = true }
konstruo_geometry = { workspace = true }

[lints]
workspace = true
