[package]
name = "konstruo_distribution"
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
konstruo_beziers = { workspace = true }
konstruo_geometry = { workspace = true }
taffy = { workspace = true }

[lints]
workspace = true

